[project]
name = "01-ukol"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ollama>=0.6.1",
    "openai>=2.8.1",
    "wikipedia>=1.4.0",
]
